version: '3.8'
services:
  postgres:
    image: postgres:14.1-alpine
    container_name: postgresql
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dbpsql
    ports:
      - '5432:5432'
  backend:
    restart: always
    build: 
      context: ../api
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production

      # API Config
      - EXPLORER_ROOT_PATH=/api
      - EXPLORER_MOUNT_PATH=/explorer

      # DB Config
      - DB_HOST=postgresql # `mysql` là tên của service mysql phía trên
      - DB_PORT=5432 # port mặc định của mysql
      - DB_NAME=dbpsql # giống phía trên
      - DB_PASSWORD=postgres # giống phía trên
      - DB_USER=postgres # mặc định là root

    depends_on:
      - postgres
  admin: 
    image: nginx:1.25.0
    ports:
      - 3001:80
    volumes:
      - ../admin/build:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
   