version: '3'
services:
  postgres:
    image: postgres:14.8
    container_name: postgresql
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dreambuilder
    ports:
      - '5432:5432'
  backend:
    restart: always
    container_name: api
    build: 
      context: ../api
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production

      # DB Config
      - DB_HOST=postgresql 
      - DB_PORT=5432 
      - DB_NAME=dreambuilder 
      - DB_PASSWORD=postgres 
      - DB_USER=postgres 

    depends_on:
      - postgres
  admin: 
    image: nginx:1.25.0
    container_name: admin
    ports:
      - 80:80
    volumes:
      - ../admin/build:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
   